### ISSUE TITLE
[개선] 증명사진 등록시 리사이징

### ISSUE THREAD

**Issue by jyj1289** [Bamdoliro/marubase#104]
### 🙌 개선 방향

현재 사진은 3cm * 4cm 규격만 유지할 수 있는데, 이를 자동으로 리사이징 하도록 변경

**Comment by gimhanul** [comment]
이미지 리사이징 기능 써봤는데 
쉽지만 화질이 엄청 깨지는 점 참고해주세요 ㅎㅎ... ^^

**Comment by jyj1289** [comment]
> 이미지 리사이징 기능 써봤는데 쉽지만 화질이 엄청 깨지는 점 참고해주세요 ㅎㅎ... ^^

그래서 프론트에서 규격맞도록 리사이징하는걸로 변경했습니다 :)
