### ISSUE TITLE
[새기능] 어드민 분석 기능

### ISSUE THREAD

**Issue by cabbage16** [Bamdoliro/marubase#79]
### ✨ 개요

어드민이 지원자 수, 성적 분포, 지원 전형 비율, 출신 학교 현황을 볼 수 있어야 합니다.

### ✅ 해야 할 일

- [x] 각 전형별 지원자 수
- [x] 성적 분포 (1, 2차, 최종별 최고점, 최하점, 평균점)
- [x] 지원 전형 비율
- [x] 출신 학교 현황
- [x] 테스트코드 작성

### 🙏🏻 요구사항

- [x] 어드민만

**Comment by gimhanul** [comment]
왜 나에게 할당을...(?) 일 시키지 말아 주세요
